### ISSUE TITLE
Return nil when the response payload is empty

### ISSUE THREAD

**Issue by sufyankhanrao** [apimatic/core-lib-ruby#42]
In the existing implementation when the response from the API Call is missing which means the raw response payload is nil or empty string including whitespaces, then return nil instead of the same payload. The fix is in the json_deserialize utility in ApiHelper class and the response handler class before applying the deserializers.
```[tasklist]
### Tasks
- [x] Add the guard clause in the `json_deserialize` utility
- [x] Return early when the raw response body is nil or empty including whitespaces
- [x] Add unit tests around the changes
```
